emamttae/board/urls.py
from django.urls import path, re_path
from .views import BoardLV, Board_POSTLV
from . import views

app_name = 'board'

urlpatterns = [
    # example : /board/
    path('', BoardLV.as_view(), name='index'),

    # example : /board/slug-example/
    re_path(r'^(?P<slug>[-\w]+)/$', views.Board_POSTLV.as_view(), name='board_detail'),

    # example : /board/slug-example/add
    re_path(r'^/add/$', views.PostCreatedView.as_view(), name='add'),

    re_path(r'^(?P<slug>[-\w]+)/(?P<week>\d{2})/$', views.Board_POSTLV_otherweeks.as_view(), name='otherweeks'),

    # example : /board/slug-example/24
    re_path(r'^(?P<slug>[-\w]+)/add/<int:week>/', views.PostCreatedView.as_view(), name='by_week'),
]

emamttae/emamttae/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
]

emamttae/board/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User



# Create your models here.
from django.urls import reverse


class Board(models.Model):
    title = models.CharField("TITLE", max_length=100)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True)
    description = models.CharField('DESCRIPTION', max_length=100, blank=True)
    created_date = models.DateField('CREATED DATE', auto_now_add=True)
    modified_date = models.DateField('MODIFIED DATE', auto_now=True)

    class Meta:
        verbose_name = 'board'
        verbose_name_plural = 'boards'
        ordering = ('-modified_date',)

    def __str__(self):
        return self.slug

    def get_absolute_url(self):
        return reverse('board:board_detail', args=(self.slug,))


class Post(models.Model):
    board = models.ForeignKey(Board,on_delete=models.CASCADE, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField('POST', max_length=100)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True)
    content = models.TextField('CONTENT')
    created_date = models.DateTimeField('CREATED DATE', default=timezone.now)
    modified_date = models.DateTimeField('MODIFIED DATE', default=timezone.now)
    created_week = models.IntegerField('CREATED_WEEK', default=timezone.now().isocalendar()[1],)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        ordering = ('-created_date',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('board:post_detail', args=self.slug, )

    def get_previous(self):
        return self.get_previous_in_order()

    def get_next(self):
        return self.get_next_in_order()

emamttae/board/views.py
import datetime

from django.shortcuts import render, get_object_or_404
from django.template import Context
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from .models import Board, Post


# ListView
class BoardLV(ListView):
    model = Board
    template_name = 'board/board_all.html'
    context_object_name = 'boards'
    paginate_by = 5


# DetailView
class Board_POSTLV(ListView):
    # model = Board
    week = datetime.datetime.now().isocalendar()[1]
    template_name = 'board/post_list.html'
    context_object_name = 'posts'

    def get_queryset(self):
        self.board_slug = self.kwargs['slug']
        return Post.objects.filter( created_week=self.week)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['week'] = self.week

        return context


class Board_POSTLV_otherweeks(ListView):
    # model = Board
    template_name = 'board/post_list.html'
    context_object_name = 'posts'

    def get_queryset(self):
        self.week = self.kwargs['week']
        return Post.objects.filter(created_week=self.week)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['week']=self.week
        return context




class PostCreatedView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content']
    success_url = reverse_lazy('board:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

emamttae/board/templates/board/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Emamttae</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" type="text/css">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">

</head>
<body style="padding-top:10px;">

<div>
        <h1><a href="/board/">EMAMTTAE</a> </h1>
</div>

<div style="padding-top:10px; padding-left:20px">
    {% block content %}{% endblock %}
</div>


</body>
</html>

emamttae/board/templates/board/board_all.html
{% extends 'board/base.html' %}


    {% block content %}
        {% for board in boards %}
          <h3><a href='{{ board.get_absolute_url }}'>{{ board.title }}</a> </h3>
            최근 업데이트 : {{ board.modified_date|date:"N d, Y" }}
            <p>{{ board.description }}</p>
        {% endfor %}
    {% endblock %}

emamttae/board/templates/board/board_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Board detail</title>
</head>


<h2>{{ object.title }}</h2>


</body>
</html>

emamttae/board/templates/board/post_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Post Create - {{user}}</h1>

    {% if form.errors %}
    {% endif %}

    <form action="." method="post" class="card pt-3">{% csrf_token %}
        <div class="form-group row">
            {{ form.title }}
            <div class="col-sm-5">
                {{ form.title}}
            </div>
        </div>

        <div class="form-group row">
            {{ form.content }}
            <div class="col-sm-5">
                {{ form.content}}
            </div>
        </div>




    </form>
</body>
</html>

emamttae/board/templates/board/post_list.html
{% extends 'board/base.html' %}


    {% block content %}
    <body>
        <div>
            <p>다른 주</p>
            <a href="01">01</a>
            <a href="02">02</a>
            <a href="03">03</a>
            <a href="04">04</a>
            <a href="05">05</a>
            <a href="06">06</a>
            <a href="07">07</a>
            <a href="08">08</a>
            <a href="09">09</a>
            <a href="10">10</a>
            <a href="11">11</a>
            <a href="12">12</a>
            <a href="13">13</a>
            <a href="14">14</a>
            <a href="15">15</a>
            <a href="16">16</a>
            <a href="17">17</a>
            <a href="18">18</a>
            <a href="19">19</a>
            <a href="20">20</a>
            <a href="21">21</a>
            <a href="22">22</a>
            <a href="23">23</a>
            <a href="24">24</a>
            <a href="25">25</a>
            <a href="26">26</a>
            <a href="27">27</a>
            <a href="28">28</a>
            <a href="29">29</a>
            <a href="30">30</a>
            <a href="31">31</a>
            <a href="32">32</a>
            <a href="33">33</a>
            <a href="34">34</a>
            <a href="35">35</a>
            <a href="36">36</a>
            <a href="37">37</a>
            <a href="38">38</a>
            <a href="39">39</a>
            <a href="40">40</a>
            <a href="41">41</a>
            <a href="42">42</a>
            <a href="43">43</a>
            <a href="44">44</a>
            <a href="45">45</a>
            <a href="46">46</a>
            <a href="47">47</a>
            <a href="48">48</a>
            <a href="49">49</a>
            <a href="50">50</a>
            <a href="51">51</a>
            <a href="52">52</a>
            <a href="53">53</a>
            <a href="54">54</a>
        </div>
        <div>

                <h2><a>{{ week }} 번째 주</a></h2>
                <h5>모든 {{ week }}번째주의 기록을 톳아봅니다</h5>
                <br>

            {% for week in weeks %}
                <p>week</p>
            {% endfor %}

        </div>

<!--        <a href="{% url 'board:add' %}"><span class="glyphicon glyphicon-plus"></span></a>-->

        {% for post in posts %}
            <h3>{{post.title}}</h3>
            <p>{{ post.created_date }}</p>
            <p>{{ post.content |linebreaks}}</p>
            <br>
        {% endfor %}
    </body>
    {% endblock %}